- name: "[CHALLENGE 6] Deploy container"
  hosts: all
  tasks:

    - name: Copy challenge-4
      ansible.builtin.copy:
        src: ../challenge-4
        dest: /tmp/
      tags:
        - configure

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      tags:
        - install

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present
      tags:
        - intasll

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest
      tags:
        - install

    - name: Install Docker
      pip:
        name: docker
      tags:
        - install

    - name: Build Dockerfile
      docker_image:
        name: challenge-6:v1.0
        source: build
        build:
          path: /tmp/challenge-4
      tags:
        - install

    - name: Deploy container
      docker_container:
        name: challenge-6
        image: challenge-6:v1.0
        ports:
          - '83:8083'
      tags:
        - always
